<a href="https://colab.research.google.com/github/watchiravitdon-lgtm/AI-DriftLab-GitHub-Ready/blob/main/workshop_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
file_path = '/content/drive/MyDrive/workshop.1/Bootcamp_2026_Workshop1_1.xlsx'
df = pd.read_excel(file_path, sheet_name='in')

In [ ]:
df.head()

,รหัส,ชื่อประกาศ,ประเภทรถ,ระบบขับเคลื่อน,เลขไมล์,ยี่ห้อ,รุ่น,รุ่นย่อย,ขนาดเครื่องยนต์,ปี,สี,เชื้อเพลิง,ระบบเกียร์,จังหวัด,ราคา
0,370611722,โตโยต้า RT100 Classiccar,Sedan,2WD,999,Toyota,RT100,NaN,1.6,1977,น้ำตาล,Petrol,MT,น่าน,15000
1,29542,1977 Mitsubishi Lancer 1.6 (ปี 76-80) Sedan,Sedan,2WD,2500,Mitsubishi,Lancer,NaN,1.6,1977,น้ำเงิน,Petrol,MT,กรุงเทพมหานคร,18000
2,370598545,1996 สามห่วง 1.6,SUV,2WD,300000,Toyota,Corolla,GXi,1.6,1996,ขาว,Petrol,AT,ชลบุรี,24500
3,370607844,Toyota Corolla เกียร์ออโต้ ลดราคาได้,SUV,2WD,NaN,Toyota,Corolla,GL,1.3,2005,NaN,Petrol,AT,นนทบุรี,25000
4,370635260,ขาย โตโยต้า corolla ตามสภาพ,Sedan,2WD,NaN,Toyota,Corolla Altis,E,1.6,2004,ขาว,Petrol,AT,กรุงเทพมหานคร,25000

In [ ]:
df.isnull().sum()

รหัส                 0
ชื่อประกาศ           0
ประเภทรถ             0
ระบบขับเคลื่อน       0
เลขไมล์            152
ยี่ห้อ               2
รุ่น                 0
รุ่นย่อย           546
ขนาดเครื่องยนต์      0
ปี                   0
สี                 438
เชื้อเพลิง           0
ระบบเกียร์           0
จังหวัด              1
ราคา                 0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,รหัส,ชื่อประกาศ,ประเภทรถ,ระบบขับเคลื่อน,เลขไมล์,ยี่ห้อ,รุ่น,รุ่นย่อย,ขนาดเครื่องยนต์,ปี,สี,เชื้อเพลิง,ระบบเกียร์,จังหวัด,ราคา
0,370611722,โตโยต้า RT100 Classiccar,Sedan,2WD,999,Toyota,RT100,NaN,1.6,1977,น้ำตาล,Petrol,MT,น่าน,15000
1,29542,1977 Mitsubishi Lancer 1.6 (ปี 76-80) Sedan,Sedan,2WD,2500,Mitsubishi,Lancer,NaN,1.6,1977,น้ำเงิน,Petrol,MT,กรุงเทพมหานคร,18000
3,370607844,Toyota Corolla เกียร์ออโต้ ลดราคาได้,SUV,2WD,NaN,Toyota,Corolla,GL,1.3,2005,NaN,Petrol,AT,นนทบุรี,25000
4,370635260,ขาย โตโยต้า corolla ตามสภาพ,Sedan,2WD,NaN,Toyota,Corolla Altis,E,1.6,2004,ขาว,Petrol,AT,กรุงเทพมหานคร,25000
5,370604126,รถมือสอง Mitsubishi Cedia ปี 04 สภาพดี ช่วงล่า...,Sedan,2WD,NaN,Mitsubishi,Lancer,Cedia,1.8,2004,ฟ้า,Petrol,AT,กรุงเทพมหานคร,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2978,8571,ขายรถ Isuzu Adventure Master 3.0 ปี2006 Wagon,Wagon,2WD,0,Isuzu,Adventure Master,-,3.0,2006,NaN,Diesel,AT,นนทบุรี,169000
2988,5168,Isuzu D-Max 3.0 CAB-4 SLX 2004 รถบ้านมือเดียวส...,Pickup,2WD,0,Isuzu,D-Max,NaN,3.0,2004,NaN,Diesel,MT,พระนครศรีอยุธยา,169000
2993,370615742,รถยนต์ Mercedes Benz,Sedan,2WD,NaN,Mercedes-Benz,S280,W140,2.8,2004,ดำ,Petrol,AT,กรุงเทพมหานคร,169000
2998,990001,2018 Toyota Yaris 1.2 มือสอง,Hatchback,2WD,85000,NaN,Yaris,E,1.2,2018,ขาว,Petrol,AT,กรุงเทพมหานคร,320000
2999,990001,2018 Toyota Yaris 1.2 มือสอง,Hatchback,2WD,85000,NaN,Yaris,E,1.2,2018,ขาว,Petrol,AT,กรุงเทพมหานคร,320000

In [ ]:
df['ยี่ห้อ'] = df['ยี่ห้อ'].fillna("ไม่ระบุ")

In [ ]:
df["ยี่ห้อ"].isnull().sum()

np.int64(0)

In [ ]:
df[df.duplicated(keep=False)]

,รหัส,ชื่อประกาศ,ประเภทรถ,ระบบขับเคลื่อน,เลขไมล์,ยี่ห้อ,รุ่น,รุ่นย่อย,ขนาดเครื่องยนต์,ปี,สี,เชื้อเพลิง,ระบบเกียร์,จังหวัด,ราคา
2998,990001,2018 Toyota Yaris 1.2 มือสอง,Hatchback,2WD,85000,ไม่ระบุ,Yaris,E,1.2,2018,ขาว,Petrol,AT,กรุงเทพมหานคร,320000
2999,990001,2018 Toyota Yaris 1.2 มือสอง,Hatchback,2WD,85000,ไม่ระบุ,Yaris,E,1.2,2018,ขาว,Petrol,AT,กรุงเทพมหานคร,320000

In [ ]:
df = df.drop_duplicates()

In [ ]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [รหัส, ชื่อประกาศ, ประเภทรถ, ระบบขับเคลื่อน, เลขไมล์, ยี่ห้อ, รุ่น, รุ่นย่อย, ขนาดเครื่องยนต์, ปี, สี, เชื้อเพลิง, ระบบเกียร์, จังหวัด, ราคา]
Index: []

In [ ]:
df.dtypes

รหัส                 int64
ชื่อประกาศ          object
ประเภทรถ            object
ระบบขับเคลื่อน      object
เลขไมล์             object
ยี่ห้อ              object
รุ่น                object
รุ่นย่อย            object
ขนาดเครื่องยนต์    float64
ปี                   int64
สี                  object
เชื้อเพลิง          object
ระบบเกียร์          object
จังหวัด             object
ราคา                 int64
dtype: object

In [ ]:
df["เลขไมล์"] = pd.to_numeric(
    df["เลขไมล์"],
    errors="coerce"
)

/tmp/ipykernel_1707/1299753809.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["เลขไมล์"] = pd.to_numeric(

In [ ]:
df.dtypes

รหัส                 int64
ชื่อประกาศ          object
ประเภทรถ            object
ระบบขับเคลื่อน      object
เลขไมล์            float64
ยี่ห้อ              object
รุ่น                object
รุ่นย่อย            object
ขนาดเครื่องยนต์    float64
ปี                   int64
สี                  object
เชื้อเพลิง          object
ระบบเกียร์          object
จังหวัด             object
ราคา                 int64
dtype: object

In [ ]:
df["ยี่ห้อ"].unique()

array(['Toyota', 'Mitsubishi', 'Nissan', 'Honda', 'Opel', 'Rover',
       'Mercedes-Benz', 'Volvo', 'Hyundai', 'Holden', 'Chevrolet', 'Ford',
       'Saab', 'Mazda', 'Audi', 'Volkswagen', 'BMW', 'Daihatsu',
       'Citroen', 'Proton', 'Isuzu', 'Kia', 'Thairung', 'Suzuki', 'MG',
       'Peugeot', 'Lexus', 'SAAB', 'Ssangyong', 'Jeep', 'DFM', 'Tata',
       'THAIRUNG', 'Land Rover', 'DEVA', 'ไม่ระบุ', 'TOYOTA'],
      dtype=object)

In [ ]:
df["ยี่ห้อ"]= df["ยี่ห้อ"].str.strip().str.title()

/tmp/ipykernel_1707/1423183272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ยี่ห้อ"]= df["ยี่ห้อ"].str.strip().str.title()

In [ ]:
df["ยี่ห้อ"].unique()

array(['Toyota', 'Mitsubishi', 'Nissan', 'Honda', 'Opel', 'Rover',
       'Mercedes-Benz', 'Volvo', 'Hyundai', 'Holden', 'Chevrolet', 'Ford',
       'Saab', 'Mazda', 'Audi', 'Volkswagen', 'Bmw', 'Daihatsu',
       'Citroen', 'Proton', 'Isuzu', 'Kia', 'Thairung', 'Suzuki', 'Mg',
       'Peugeot', 'Lexus', 'Ssangyong', 'Jeep', 'Dfm', 'Tata',
       'Land Rover', 'Deva', 'ไม่ระบุ'], dtype=object)

In [ ]:
df["อายุรถ"] = 2026-df['ปี']

In [ ]:
df.head()

,รหัส,ชื่อประกาศ,ประเภทรถ,ระบบขับเคลื่อน,เลขไมล์,ยี่ห้อ,รุ่น,รุ่นย่อย,ขนาดเครื่องยนต์,ปี,สี,เชื้อเพลิง,ระบบเกียร์,จังหวัด,ราคา
0,370611722,โตโยต้า RT100 Classiccar,Sedan,2WD,999.0,Toyota,RT100,NaN,1.6,1977,น้ำตาล,Petrol,MT,น่าน,15000
1,29542,1977 Mitsubishi Lancer 1.6 (ปี 76-80) Sedan,Sedan,2WD,2500.0,Mitsubishi,Lancer,NaN,1.6,1977,น้ำเงิน,Petrol,MT,กรุงเทพมหานคร,18000
2,370598545,1996 สามห่วง 1.6,SUV,2WD,300000.0,Toyota,Corolla,GXi,1.6,1996,ขาว,Petrol,AT,ชลบุรี,24500
3,370607844,Toyota Corolla เกียร์ออโต้ ลดราคาได้,SUV,2WD,NaN,Toyota,Corolla,GL,1.3,2005,NaN,Petrol,AT,นนทบุรี,25000
4,370635260,ขาย โตโยต้า corolla ตามสภาพ,Sedan,2WD,NaN,Toyota,Corolla Altis,E,1.6,2004,ขาว,Petrol,AT,กรุงเทพมหานคร,25000